[client]
# Показывать меню в боковой панели
showSidebarNavigation = true
# initial_sidebar_state="auto"

[theme]
primaryColor="#5F9EA0"
backgroundColor="#D3D3D3"
# backgroundColor="#f0f0f5"
# secondaryBackgroundColor="#e0e0ef"
secondaryBackgroundColor="#40E0D0"
textColor="#262730"
font="sans serif"
baseFontSize=16
